name: Python Format

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Black
      run: |
        pip install black
        black 
    github_token:
      description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
      required: true
    repository:
      description: 'Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
      default: ''
      required: false
    branch:
      description: 'Destination branch to push changes'
      required: false
      default: 'master'
    force:
      description: 'Determines if force push is used'
      required: false
    tags:
      description: 'Determines if --tags is used'
      required: false
    directory:
      description: 'Directory to change to before pushing.'
      required: false
      default: '.'
    runs:
      using: 'node12'
      main: 'action.js'
